import React from 'react';
import { View, Text, Image, StyleSheet, TouchableOpacity } from 'react-native';
import { useNavigation, useRoute } from '@react-navigation/native';

const ResultsDisplay = () => {
  const navigation = useNavigation();
  const route = useRoute();
  const { purpose } = route.params || {};

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Your Perfect Photo</Text>

      <View style={styles.row}>
        <View style={styles.imageWrapper}>
          <Image
            source={{ uri: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' }}
            style={styles.image}
            resizeMode="contain"
          />
        </View>

        <View style={styles.feedbackWrapper}>
          <View style={styles.card}>
            <Text style={styles.cardTitle}>
              Why This Works for {purpose}
            </Text>
            <Text style={styles.cardText}>
              Feedback will appear here once it's generated by our AI engine.
            </Text>
          </View>

          <TouchableOpacity
            style={styles.button}
            onPress={() => navigation.navigate('UploadPhotos')}
          >
            <Text style={styles.buttonText}>Try Again with New Photos</Text>
          </TouchableOpacity>
        </View>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: 20,
    backgroundColor: '#0a0a23',
    borderRadius: 10,
    flex: 1,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 40,
    color: 'gold',
    paddingTop: 40,
    textAlign: 'center',
  },
  row: {
    flexDirection: 'column',
  },
  imageWrapper: {
    marginBottom: 20,
    backgroundColor: '#1a1a2e',
    padding: 8,
    borderRadius: 10,
  },
  image: {
    width: '100%',
    height: 300,
    borderRadius: 10,
  },
  feedbackWrapper: {
    gap: 12,
  },
  card: {
    backgroundColor: '#2b2b3c',
    padding: 16,
    borderRadius: 10,
  },
  cardTitle: {
    fontSize: 18,
    color: 'gold',
    fontWeight: '600',
    marginBottom: 8,
  },
  cardText: {
    color: '#ddd',
    fontSize: 14,
  },
  button: {
    marginTop: 20,
    alignSelf: 'center',
    backgroundColor: 'gold',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
  },
  buttonText: {
    color: '#1a1a2e',
    fontWeight: 'bold',
    fontSize: 16,
  },
});

export default ResultsDisplay;
